# Generated by Django 5.0.1 on 2024-01-24 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_title_jobpost_description_jobpost_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='title',
            field=models.CharField(default=datetime.datetime(2024, 1, 24, 12, 19, 52, 55193, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
    ]
